version: '3'
services:
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  chat_server:
    build:
      context: '.'
      args:
        - RAILS_ENV=production
    restart: always
    entrypoint: ['bash', '/app/entrypoint.sh']
    container_name: chat_server_latest
    ports:
      - "80:8000"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
    links:
      - 'postgres:postgres'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 1030 cable/config.ru
    ports:
      - '1030:1030'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  chat_server_serveo:
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: "ssh -R chat_server2019:80:chat_server:8000 -o \"StrictHostKeyChecking no\" serveo.net"

  cable_serveo:
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
    # see https://serveo.net/ for more options
    command: "ssh -R chat_server2019:1030:cable:1030 -o \"StrictHostKeyChecking no\" serveo.net"

volumes:
  postgres:
  chat_server:
  redis:
